version: '3.8'
services:
  backend:
    build: .
    container_name: it-support-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracledb:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=ticket_admin
      - SPRING_DATASOURCE_PASSWORD=M3hdi@2025!
    depends_on:
      - oracledb

  oracledb:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_PDB=XEPDB1
    ports:
      - "1521:1521"  # Mappez le port 1521 du conteneur sur le port 1521 de l'hôte
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: